DirectoryPath: ./public
IgnoreDirectoryMissingTrailingSlash: true
# This is to prevent quite so many 403 errors from external sites
HTTPHeaders: 
  User-Agent: GFSC/123
# These generate 403 errors no matter what we change so we can't check these
IgnoreURLs:
  - discord.com
  - greatermanchester-ca.gov.uk/ 
  - journals.sagepub.com
  - poeditor.com
  - pnas.org
  - raytheon.co.uk
  - tandfonline.com
  - twitter.com
