name: Weekly checks
on:
  workflow_dispatch:
  schedule:
  - cron: 0 14 * * 5

jobs:
  run-html-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Hugo Broken Link Check
        uses: marccampbell/hugo-linkcheck-action@v0.1.3
