name: Weekly checks
on:
  workflow_dispatch:
  schedule:
  - cron: 0 14 * * 5

jobs:
  run-html-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true
      - name: Run Hugo
        run: hugo
      - name: Test HTML
        continue-on-error: false
        uses: wjdp/htmltest-action@master
